#!/bin/bash
### SBATCH --partition=debug
###SBATCH --partition=general
### SBATCH --partition=lo-core # This can be as long as 7 days
#SBATCH --partition=priority
#SBATCH --account=chl23026
#SBATCH --qos=chl23026
#SBATCH --constraint=epyc128 # This is optional
#SBATCH --nodes=1
#SBATCH --ntasks=126
#SBATCH --time=24:00:00
#SBATCH --mail-user=duc.nguyen@uconn.edu      # Destination email address
#SBATCH --mail-type=ALL                       # Event(s) that triggers email notification
#SBATCH --job-name=matlab_job
#SBATCH --output=matlab_output_%j
export SLURM_EXPORT_ENV=ALL
#export I_MPI_FABRICS=shm,tcp

##the slurm number to restart simulation... This need full state to be stored.
SUBMITDIR=$SLURM_SUBMIT_DIR
WORKDIR=/scratch/chl23026/jms24002/matlab_$SLURM_JOB_ID
mkdir -p "$WORKDIR" && cp -r *.m "$WORKDIR" && cp submit_matlab_uconn "$WORKDIR" && cd "$WORKDIR" || exit -1


# Required modules
module load matlab

# Run MATLAB executable
matlab -nodisplay -nosplash -nodesktop -r maxGrowthRateMap_RiPe_Rp2_tau0_01\; exit\;


cd "$SUBMITDIR" && cp matlab_output_$SLURM_JOB_ID "$WORKDIR"

